### ISSUE TITLE
BUG: 更新文件，会额外的添加分割线

### ISSUE THREAD

**Issue by YIRU69** [1657744680/obsidian-yaml-database#1]
你好，感谢你的分享，你的插件对我来说很有用，我第一时间就尝试了
但是在使用中有问题出现，个人感觉还是比较大的问题
1. 我使用修改yaml名称的操作，它会额外的在笔记里面添加两条"---"，这个会发现在没有yaml区的文件，一般这个文件是模板文件
2. 建议增加文件夹排除

**Comment by YIRU69** [comment]
3.希望支持批量修改文中的值或文本
4. 希望增加对索引出现的文件，进行选择式的修改

**Comment by GodDown1V4** [comment]
> 你好，感谢你的分享，你的插件对我来说很有用，我第一时间就尝试了 但是在使用中有问题出现，个人感觉还是比较大的问题
> 
> 1. 我使用修改yaml名称的操作，它会额外的在笔记里面添加两条"---"，这个会发现在没有yaml区的文件，一般这个文件是模板文件
> 2. 建议增加文件夹排除

首先感谢使用和反馈😄
对于1，这个是我设计的这个逻辑问题，回来会进行修改
2回来也会加上

**Comment by GodDown1V4** [comment]
> 3.希望支持批量修改文中的值或文本
> 4. 希望增加对索引出现的文件，进行选择式的修改

对于3的话目前没有考虑，因为插件就是yaml修改。
4的话原本也考虑过（以前做过这种类似的），不过太麻烦了😢可能后边一点的版本会添加这个功能

**Comment by 1657744680** [comment]
> 你好，感谢你的分享，你的插件对我来说很有用，我第一时间就尝试了 但是在使用中有问题出现，个人感觉还是比较大的问题
> 
> 1. 我使用修改yaml名称的操作，它会额外的在笔记里面添加两条"---"，这个会发现在没有yaml区的文件，一般这个文件是模板文件
> 2. 建议增加文件夹排除

**Comment by 1657744680** [comment]
> 4. 希望增加对索引出现的文件，进行选择式的修改

**Comment by GodDown1V4** [comment]
- [x] 2. 建议增加文件夹排除
- [x] 4. 希望增加对索引出现的文件，进行选择式的修改

**Comment by YIRU69** [comment]
感谢回复，希望做的更好
