### ISSUE TITLE
“表格设置”无法正常显示

### ISSUE THREAD

**Issue by EaMarWi** [1657744680/obsidian-yaml-database#13]
大佬我出现了一个问题：“表格设置”无法正常显示，即使是在一个完全干净的Obsidian库里面，不知道是什么问题引起的。
![图片](https://raw.githubusercontent.com/MeerOst/RaumzeitBlogPicturesCDN/master/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-04-11%20193058.png)
![](https://raw.githubusercontent.com/MeerOst/RaumzeitBlogPicturesCDN/master/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-04-11%20193145.png)

**Comment by GodDown1V4** [comment]
等我今天晚上会发布个新的，新版本更改了逻辑，在闪烁上上有很大改善

**Comment by EaMarWi** [comment]
好的，感谢大佬
