### ISSUE TITLE
给文档加新属性会出错

### ISSUE THREAD

**Issue by RuJingTingShan** [1657744680/obsidian-yaml-database#16]
文档里没有任何yaml，我用这个插件就是为了给旧文档批量增加YAML
编辑列--右键--新属性（操作逻辑有点复杂），输入新属性之后返回一个error页面
但是新属性已经创立了，yaml已经写入全部的文件，重复上面的操作才能看到。

另外还有一个问题，我加的tags正常都是不带双引号的，用这种方式加的tags是默认双引号，会有什么使用上的问题吗？
刚想起来还有一个问题，新家的yaml支持templater的语法吗？例如我想给所有的yaml加入`创建时间`一个属性，需要用到`<% tp.file.creation_date() %>`语句

**Comment by GodDown1V4** [comment]
bug已修复

加上单引号并不会对标签的识别造成影响

现在不支持templates模板创建，我回来看看templates吧
