### ISSUE TITLE
BUG反馈：在文件夹里面没有一个笔记文件的时候创建属性的相关BUG

### ISSUE THREAD

**Issue by EaMarWi** [1657744680/obsidian-yaml-database#19]
以下情况是在文件夹里面没有一个笔记文件的时候发生：

1.在编辑模式下创建的属性，无法在阅读模式下出现（表格里面没有出现，属性显隐控制设置里面也没有出现）
2.同样情况，在阅读模式下创建的属性，无法在编辑模式下显示。
3.如果创建属性后点击刷新，属性会一个一个消失（在编辑模式和阅读模式下都会发生）。

这是我认为的BUG，因为按照习惯，一般是新建表格，再创建笔记文件，所以存在文件夹里面没有文件仍然需要创建属性的需要。

**Comment by GodDown1V4** [comment]
这个是表格属性的逻辑问题，回来我改改
