### ISSUE TITLE
使用代码块显示bug

### ISSUE THREAD

**Issue by limrli** [1657744680/obsidian-yaml-database#2]
yaml区标签比较多就会显示bu
![tmpAE46](https://user-images.githubusercontent.com/68333993/160650776-618ad40c-ac04-4777-bab2-a2ba5c06835f.png)
g

**Comment by GodDown1V4** [comment]
这个时插件的css样式被第三方主题覆盖，目前我在等会csss的老哥做。
暂时的办法就是使用`prop:`来选择显示的属性，让属性显示少一点。

**Comment by GodDown1V4** [comment]
已经由 @cumany 老哥修复了
