### ISSUE TITLE
建议：优化表格

### ISSUE THREAD

**Issue by EaMarWi** [1657744680/obsidian-yaml-database#20]
感谢大佬的作品，一直想转OB，奈何依赖notion的database，今偶遇大佬作品，如获珍宝。

但是感觉目前操作上还是有些不方便，所以提一下建议：
> 1.可以取消"编辑列"这个按钮的操作吗？这个多的步骤感觉体验不是很好。
>> 建议：让用户可以直接编辑，无需点击“编辑列”，并且能够自动保存，无需点击”应用变更”

> 2.进行添加属性的操作时，需要在已经有的属性上右键，然后点击添加属性，但是在填写属性名称时会覆盖已经有属性名称，在填写结束后停止覆盖。这有些影响观感和体验。
>> 建议：在列的最后添加一个“+”号，让用户直接点击添加属性，优化操作也提升观感。

> 3.在编辑模式下表格的最后一行存在显示问题，即那个：1 to 1 of 1，page 1 of page。希望可以优化。

> 4.关于表格数据文件的保存方式：
目前博主采用的是保存在插件文件夹里面的方式。虽然避免了json数据太导致页面显示杂乱无章的问题。但是会有一些问题：（1）保存在单个json文件里面，如果表格数据多了之后，可能会造成卡顿。（2）保存在插件文件夹里面，不方便同步插件同步。虽然有些插件有同步配置文件的选项，但是毕竟不同端配置文件有差异，同步配置文件可能出现问题。
>> 建议：数据文件保存在存数据表页面的那个文件夹下。

> 5.目前创建新表，需要自己手动写＂'''yamledit ……＂
>> 建议：可以在斜杠命令下添加＂一键添加表格的操作＂，并且能够自动填写编号，避免编号重复和编号填写麻烦的问题。

这是我最期待的一款插件，他不同于dataview，他是简单表格和dataview的结合体，既有简单表格的轻便，也有数据查询与汇总的高级。我希望有朝一日，该插件能像dataview一样走在社区的前列。由于我不会编程，也帮不上什么忙，希望大佬能够继续坚持，作品越来越完美。感谢！

**Comment by GodDown1V4** [comment]
感谢建议！
1、这个aggrid的表头添加面版是企业版的(付费而且很贵)，所以目前只能使用一个自定义表头。(以后有空的话可以考虑把表头功能全都移植到自定义表头)

2、4、5会考虑，4是很不错的建议，2的话回来看看能不能实现(有可能是在操作区域显示)

3的话是这个表格组件自带的分页，我自己做的话肯定没他这个好用。

建议很不错，多谢。但是我这几天都很忙，估计5月多可能能有空。
