### ISSUE TITLE
功能请求：建议支持对子文件夹的批量处理

### ISSUE THREAD

**Issue by tyf2018** [1657744680/obsidian-yaml-database#21]
记得以前是支持对子文件夹进行批量处理，非常方便，建议加回此功能，或者以别的方式实现对子文件夹的批量处理功能，谢谢

对我而言，遍历子文件夹，是刚需，期待大神能考虑一下

**Comment by GodDown1V4** [comment]
回来会考虑在设置项里增加一个遍历子文件夹的设置项。

**Comment by GodDown1V4** [comment]
如果加上子文件夹内的文档遍历会出现一些功能限制。
比如说新建文档时会在表格所管理的文件夹中建立而不是该文件夹的子文件夹

**Comment by tyf2018** [comment]
> 如果加上子文件夹内的文档遍历会出现一些功能限制

只要能遍历子文件夹+批量新增/编辑yaml属性，对我而言就足够。为了上述需求，我已经回退到旧版本了

**Comment by GodDown1V4** [comment]
> > 如果加上子文件夹内的文档遍历会出现一些功能限制
> 
> 只要能遍历子文件夹+批量新增/编辑yaml属性，对我而言就足够。为了上述需求，我已经回退到旧版本了
> 
> 

现在最新版是新增属性不会立即为文档添加属性，而是只有在使用表格更改属性值的时候才会为文档添加或者修改属性。

而且这个文件夹下的所有文档不可以重名。

**Comment by tyf2018** [comment]
🤣那我还是老老实实用旧版吧

**Comment by tyf2018** [comment]
> 而是只有在使用表格更改属性值的时候才会为文档添加或者修改属性。

我都是通过表格来批量编辑的。另外请问后续不会考虑加回 遍历子文件夹的功能了，是么？

**Comment by GodDown1V4** [comment]
> > 而是只有在使用表格更改属性值的时候才会为文档添加或者修改属性。
> 
> 我都是通过表格来批量编辑的。另外请问后续不会考虑加回 遍历子文件夹的功能了，是么？
> 
> 
> 

目前除了你好像没其他人提遍历子文件夹的需求。如果你用旧版本的话我就不准备加了。
而且现在这个插件新版本主要目标是notion的database的表格视图，已经不是单纯的批量编辑yaml了

**Comment by tyf2018** [comment]
好吧，收到
