### ISSUE TITLE
建议：优化Filter的编辑方框

### ISSUE THREAD

**Issue by EaMarWi** [1657744680/obsidian-yaml-database#23]
目前点击“三”后，进行筛选时，跳出的编辑框限制在表格内，导致在行数据较少时，不方便编辑，希望能够优化一下。
![截图](https://raw.githubusercontent.com/MeerOst/MeerOstDrawingBed/main/%E6%8D%95%E8%8E%B7.PNG)
### 大佬辛苦了！

**Comment by GodDown1V4** [comment]
这个是aggrid自带的，你行数比较多(可能也就三四行就够了)的时候它就显示完整了。就这样先凑合着用吧😂

**Comment by EaMarWi** [comment]
好吧，对了，在编辑文件名称时会存在，旧名称阴影问题，不知道是不是AGtable的问题？
![截图](https://raw.githubusercontent.com/MeerOst/MeerOstDrawingBed/main/123.PNG)

**Comment by GodDown1V4** [comment]
我回来瞅瞅，是只有文件重命名的时候会这样吗？

**Comment by EaMarWi** [comment]
嗯，目前只在表格中编辑文件名时出现。
对了，可以在编辑模式和阅读模式切换时，自动刷新一次吗？目前在编辑模式或者阅读模式下编辑，然后再切换模式时，另一种模式的表格还处于原先的样式，需要手动刷新一次。

**Comment by GodDown1V4** [comment]
处于原先的样式是什么意思？

好像只有更改代码块中的内容时这个代码块才会重新渲染，所以还是手动切换文件来重新渲染一下吧。

**Comment by EaMarWi** [comment]
目前的感觉是，编辑模式下与阅读模式下是用不同的文件渲染一般。
在编辑模式下编辑文件名等数据后，再刷新，最后切换回阅读模式，阅读模式的样式和数据并没有更改。

**Comment by GodDown1V4** [comment]
你是说预览和阅读这两个模式吧？

**Comment by EaMarWi** [comment]
> 你是说预览和阅读这两个模式吧？

应该是吧，目前我说的环境是，分为编辑视图和阅读视图（编辑视图是实时预览）

**Comment by GodDown1V4** [comment]
> 好吧，对了，在编辑文件名称时会存在，旧名称阴影问题，不知道是不是AGtable的问题？
> ![截图](https://raw.githubusercontent.com/MeerOst/MeerOstDrawingBed/main/123.PNG)

我这里并没有出现这种状况，可能和你的主题有关系

**Comment by GodDown1V4** [comment]
> 嗯，目前只在表格中编辑文件名时出现。
> 对了，可以在编辑模式和阅读模式切换时，自动刷新一次吗？目前在编辑模式或者阅读模式下编辑，然后再切换模式时，另一种模式的表格还处于原先的样式，需要手动刷新一次。

这个应该是和obsidian本身的实时预览有关，他这个实时预览是重新渲染了另一个表格，和阅读模式下表格不是同一个。我也没找到监听这个阅读模式切换的事件。

所以目前就先手动刷新吧，因为设置定时查询的话也会有一些问题，可能会导致资源占用无法释放。

**Comment by EaMarWi** [comment]
好的
还有一个BUG，在表格新建一个文件，表格会显示两个文件名：
这里新建了两个，就显示了四个
![截图](https://raw.githubusercontent.com/MeerOst/MeerOstDrawingBed/main/12313132.PNG)

**Comment by GodDown1V4** [comment]
> 好的
> 还有一个BUG，在表格新建一个文件，表格会显示两个文件名：
> 这里新建了两个，就显示了四个
> ![截图](https://raw.githubusercontent.com/MeerOst/MeerOstDrawingBed/main/12313132.PNG)

这个不是bug，是新建的文件会放在最上面，你重命名之后它就会取消置顶了。
因为当你行数太多时，如果新建的行不放在最上面，那样不方便编辑

**Comment by EaMarWi** [comment]
哈哈，了解了
只是看着怪，但是你这一说，就感觉挺方便的
