### ISSUE TITLE
希望可以支持本地图片和Gif格式的展示。

### ISSUE THREAD

**Issue by PencilMing** [1657744680/obsidian-yaml-database#24]
就像Notion的gallery一样，可以选择展示一些gif动图。感觉可玩性就更高了。（我是一个动态设计师，正在找怎么把一些动态效果直观展示并且能链接到制作方法和使用过这个效果的项目。所以这个需求感觉对设计师与动态设计人员会有很大帮助）

**Comment by GodDown1V4** [comment]
新版本已经支持了本地图片
