### ISSUE TITLE
不知道可不可以像这种类型方式展示。

### ISSUE THREAD

**Issue by PencilMing** [1657744680/obsidian-yaml-database#25]
不知道可不可以结合这个主题里影评展示的方式。
https://github.com/kepano/obsidian-minimal
<img width="930" alt="image" src="https://user-images.githubusercontent.com/82462283/165573518-bbc515a3-7b20-4287-b8c4-b126578e2f34.png">

**Comment by GodDown1V4** [comment]
我对CSS不了解，如果要做这个需要这方面的大佬帮助，而且aggrid的说明文档里提到过最好不要大刀阔斧的更改aggrid的表格结构。所以目前不准备这样做
