### ISSUE TITLE
BUG：配置信息存储位置设置的相关BUG

### ISSUE THREAD

**Issue by EaMarWi** [1657744680/obsidian-yaml-database#27]
复现：当用户之前设置配置信息存储的位置为`测试`文件夹，之后卸载`yaml-database`插件，再重装回来（基于42-BART插件）。
当用户再次设置配置信息存储的位置为`测试`文件夹时，无法起效（点击`应用变更`没用效果）。这时需要删除根文件夹下的`YAML Database Config.json`文件，再设置配置信息存储的位置为”测试”文件夹才能起效。

（目前看来这个问题只有卸载重装`yaml-database`插件时会出现，当用户已经安装插件并设置好配置文件存储位置后，再更换存储位置时并不会出现问题。）

因为有时需要卸载重装，所以希望大佬能修复。

**Comment by GodDown1V4** [comment]
已修复
