### ISSUE TITLE
右键文件夹直接生成索引文件

### ISSUE THREAD

**Issue by Tony-zf1** [1657744680/obsidian-yaml-database#31]
请问能不能像db folder插件和folder note插件一样，右键文件夹直接生成索引表格，索引文件可以设置为`库根目录或者指定目录`，索引表格直接链接到对应的文件夹，表格id可以自定义生成规则，比如`文件夹名+时间戳`这种。

我最近一直重度使用这个插件，体验很棒，不会像db-folder一样丢数据，非常感谢！如果能加上这个功能就更方便啦

**Comment by GodDown1V4** [comment]
已经停止维护了，学业繁重。感谢支持
![IMG_20220518_152101.jpg](https://user-images.githubusercontent.com/39726621/168980838-f5a187c1-1492-428b-b657-f480b52648d1.jpg)

**Comment by Tony-zf1** [comment]
> 已经停止维护了，学业繁重。感谢支持 

好的，学习为重哈，现在版本也已经足够好用了，感谢！
