### ISSUE TITLE
yaml表格编辑：能否自动换行？+紧凑列宽

### ISSUE THREAD

**Issue by tyf2018** [1657744680/obsidian-yaml-database#4]
很赞的插件，谢谢。

使用中遇到一个小问题： 
1、无法自动换行，当文件名稍长、或yaml字段稍多，就总会有部分内容被遮挡，需要拖动滚动条（如果笔记数量一多，就需要先滚动到表格底部，然后才能拖动滚动条，非常不方便）
2、列宽不够紧凑，浪费了很多空间。我的笔记数量较多，yaml字段也不少，紧凑一点，就不需要拖动滚动条了

建议：

1. 自动换行
2. 自动调整列宽，并尽可能紧凑（或者让用户决定是紧凑还是宽松）

**Comment by GodDown1V4** [comment]
已经由 @cumany 老哥修复了
现在已经可以换行了
至于字段数较多的问题，您也可以选择使用`prop:属性名1,属性名2……`来显示您想要展示的属性
