### ISSUE TITLE
能像tagswrangler，批量修改yaml里面的标签不？

### ISSUE THREAD

**Issue by Peingxious** [1657744680/obsidian-yaml-database#5]
看到你的B站视频，就下了用了。还以为能够批量修改yaml里面的其中一个tags。结果能替换，但是只能批量替换成一个。
万幸啊万幸，我没有备份笔记。我的tags全丢了。打了一天都没有打完。

能提升一个页面，在yaml中添加和删除标签的浮动面板？直接把多个标签全部打在yaml中！这样yaml会好用很多。

**Comment by 1657744680** [comment]
首先这个不算bug

批量更改yaml属性值是对筛选文档的一个yaml属性进行批量赋值，赋值的话肯定是你输入什么，他就赋值什么。

备份文件的事情我说过挺多遍了，B站视频简介和readme文档都在开头就说了。

对一个标签进行重新修改我这个插件应该不会考虑这个功能。

**Comment by GodDown1V4** [comment]
> 看到你的B站视频，就下了用了。还以为能够批量修改yaml里面的其中一个tags。结果能替换，但是只能批量替换成一个。
> 万幸啊万幸，我没有备份笔记。我的tags全丢了。打了一天都没有打完。
> 
> 能提升一个页面，在yaml中添加和删除标签的浮动面板？直接把多个标签全部打在yaml中！这样yaml会好用很多。

首先这个不算bug

批量更改yaml属性值是对筛选文档的一个yaml属性进行批量赋值，赋值的话肯定是你输入什么，他就赋值什么。

备份文件的事情我说过挺多遍了，B站视频简介和readme文档都在开头就说了。

对一个标签进行重新修改我这个插件应该不会考虑这个功能。

**Comment by GodDown1V4** [comment]
目前在做表格编辑yaml，还没有找到好的方式来显示修改yaml属性中的列表形式的内容，所以暂时对于tags之类的值为列表的属性还是以字符串来显示。
