### ISSUE TITLE
表格编辑模式下，请问如何自定义鼠标悬停时的字体颜色？

### ISSUE THREAD

**Issue by tyf2018** [1657744680/obsidian-yaml-database#9]
表格编辑模式下，请问如何自定义鼠标悬停时的字体颜色？

目前鼠标悬停时，字体颜色与背景色很相近（如下述截图所示），难以辨识。暂时没找到css的相关参数是什么

谢谢！

![2022-04-03_11-32-44](https://user-images.githubusercontent.com/56342788/161410167-5b403d1c-9992-49b6-92ac-c6cea50cfc43.jpg)

**Comment by GodDown1V4** [comment]
请问您使用的是哪个版本？

**Comment by tyf2018** [comment]
> 请问您使用的是哪个版本？

插件版本：	"id": "yaml-bulk-edit",
	"name": "YAML属性批量管理",
	"version": "0.5.1",

ob版本：0.14.5

另外亮色模式下是正常的，但暗黑模式会出现上述问题（换默认主题也有此问题）

**Comment by GodDown1V4** [comment]
![image](https://user-images.githubusercontent.com/39726621/161410614-0d4f5805-c1f0-45db-b245-852f9516affe.png)
我试了试，并没有这个问题，您可以尝试重新安装插件。

**Comment by tyf2018** [comment]
@1657744680 重装后问题仍在，可能是主题的原因。能告诉我css参数是什么吗？我自己修改就行

**Comment by GodDown1V4** [comment]
这个css是由 @cumany 提供支持的，我对CSS问题不懂。你是不是本地有css文件覆盖了？

**Comment by tyf2018** [comment]
谢谢解答。找到原因了，问题应该已经解决，但现在遇到另一个问题，插件渲染不出表格了。我晚点可能会另外反馈一个issue

**Comment by tyf2018** [comment]
> 但现在遇到另一个问题，插件渲染不出表格了。我晚点可能会另外反馈一个issue

原来是新版插件必须要写上id。新版强大了很多，赞！
